#!/bin/bash
set -e

. "${BASH_SOURCE%/*}/utils/print_header"

INPUT_CSV="${BASH_SOURCE%/*}/lichess_db_puzzle.csv"
DB_FILE="${BASH_SOURCE%/*}/puzzfinder.db"
SCHEMA_FILE="${BASH_SOURCE%/*}/sql/schema.sql"
INDEXES_FILE="${BASH_SOURCE%/*}/sql/indexes.sql"

rm -f "$DB_FILE"

if [ ! -f "$INPUT_CSV" ]; then
	print_header "Getting .csv"
	wget https://database.lichess.org/lichess_db_puzzle.csv.zst
	zstd -d lichess_db_puzzle.csv.zst && rm lichess_db_puzzle.csv.zst
fi

print_header "Inserting schema"
duckdb "$DB_FILE" -f "$SCHEMA_FILE"

print_header "Importing data"
. "${BASH_SOURCE%/*}/database/import"

print_header "Creating indexes"
duckdb "$DB_FILE" -f "$INDEXES_FILE"

print_header "Database created"
