#!/bin/bash

. "${BASH_SOURCE%/*}"/"scripts/themes_list"
. "${BASH_SOURCE%/*}"/"scripts/print_header"

INPUT_CSV="${BASH_SOURCE%/*}/lichess_db_puzzle.csv"
DB_FILE="${BASH_SOURCE%/*}/puzzfinder.db"
SCHEMA_FILE="${BASH_SOURCE%/*}/sql/schema.sql"
INDEXES_FILE="${BASH_SOURCE%/*}/sql/indexes.sql"

if [ ! -f "$DB_FILE" ] && [ ! -f "$INPUT_CSV" ]; then
	print_header "Getting .csv"
	wget https://database.lichess.org/lichess_db_puzzle.csv.zst
	zstd -d lichess_db_puzzle.csv.zst && rm lichess_db_puzzle.csv.zst
fi

print_header "Inserting schema"
sqlite3 "$DB_FILE" < "$SCHEMA_FILE"

print_header "Importing data"
. "${BASH_SOURCE%/*}"/"scripts/database_import"

print_header "Creating indexes"
sqlite3 "$DB_FILE" < "$INDEXES_FILE"

print_header "Database created"
