#!/bin/bash

. "${BASH_SOURCE%/*}/../themes/list"

mask_expr="(0::HUGEINT)"
for i in "${!THEMES[@]}"; do
	mask_expr+=" | (CASE WHEN list_contains(string_split(themes, ' '), '${THEMES[$i]}') THEN 1::HUGEINT << $i ELSE 0 END)"
done

duckdb "$DB_FILE" -c "
INSERT INTO puzzles
SELECT
    puzzleid AS puzzleId,
    fen,
    moves,
    (length(moves) - length(replace(moves, ' ', '')) + 1) / 2 AS movesNumber,
    rating,
    ratingdeviation AS ratingDeviation,
    popularity,
    nbplays AS nbPlays,
    gameurl AS gameUrl,
    openingtags AS openingTags,
    ${mask_expr} AS theme_mask
FROM read_csv('$INPUT_CSV');
"
