#!/bin/bash

duckdb "$DB_FILE" <<EOF
INSERT INTO puzzles
SELECT
    puzzleid AS puzzleId,
    fen,
    moves,
    (length(moves) - length(replace(moves, ' ', '')) + 1) / 2 AS movesNumber,
    rating,
    ratingdeviation AS ratingDeviation,
    popularity,
    nbplays AS nbPlays,
    gameurl AS gameUrl,
    openingtags AS openingTags,
    string_split(themes, ' ') AS themes
FROM read_csv_auto('$INPUT_CSV');
EOF
