#!/bin/bash

print_header() {
	local ascii="
   _______________  
8 |_|#|_|#|_|#|_|#| 
7 |#|_|#|_|#|_|#|_| 
6 |_|#|_|#|_|#|_|#| 
5 |#|_|#|_|#|_|#|_| 
4 |_|#|_|#|_|#|_|#| 
3 |#|_|#|_|#|_|#|_| 
2 |_|#|_|#|_|#|_|#| 
1 |#|_|#|_|#|_|#|_| 
   a b c d e f g h  "

	printf "\033[0;34m" # Blue

	echo "${ascii//$'\n'/$'\n\t'}"

	local width=$(($(echo "$ascii" | wc -L) - 2))

	local text="$*"
	local left_pad=$(((width - ${#text}) / 2))
	local right_pad=$((width - ${#text} - left_pad))

	printf "\n\t>%*s%s%*s<\033[0m\n\n" $left_pad "" "$text" $right_pad ""
}
