#!/bin/bash

{
	echo "CREATE INDEX idx_puzzles_rating ON puzzles(rating);"
	echo "CREATE INDEX idx_puzzles_movesNumber ON puzzles(movesNumber);"
	echo "CREATE INDEX idx_puzzles_popularity ON puzzles(popularity);"
	echo "CREATE INDEX idx_puzzles_nbPlays ON puzzles(nbPlays);"

	echo -e "\n-- $PRAYER"

	for theme in ${THEMES[@]}; do
		theme="theme_$theme"
		echo "CREATE INDEX idx_puzzles_$theme ON puzzles($theme) WHERE $theme = 1;"
	done
} > $INDEXES_FILE

sqlite3 $DB_FILE < $INDEXES_FILE
