#!/bin/bash

{
	echo "CREATE INDEX idx_puzzles_rating ON puzzles(rating);"
	echo "CREATE INDEX idx_puzzles_movesNumber ON puzzles(movesNumber);"
	echo "CREATE INDEX idx_puzzles_popularity ON puzzles(popularity);"
	echo "CREATE INDEX idx_puzzles_nbPlays ON puzzles(nbPlays);"
} > $INDEXES_FILE

sqlite3 $DB_FILE < $INDEXES_FILE
