#!/bin/bash

{
	echo "CREATE TABLE puzzles ("
	echo "    puzzleId TEXT PRIMARY KEY,"
	echo "    fen TEXT NOT NULL,"
	echo "    moves TEXT NOT NULL,"
	echo "    movesNumber INTEGER NOT NULL,"
	echo "    rating INTEGER NOT NULL,"
	echo "    ratingDeviation INTEGER NOT NULL,"
	echo "    popularity INTEGER NOT NULL,"
	echo "    nbPlays INTEGER NOT NULL,"
	echo "    gameUrl TEXT NOT NULL,"
	echo "    openingTags TEXT,"

	echo -e "\n    -- $PRAYER"

	for theme in ${THEMES[@]}; do
		theme="theme_$theme"
		echo "    ${theme} BOOLEAN NOT NULL,"
	done

	echo ");"
} | tac | sed "2s/,$//" | tac > $SCHEMA_FILE # removes last theme's trailing comma

# Create database and schema
sqlite3 $DB_FILE < $SCHEMA_FILE
